sistema/cde/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
app_name = 'cde'
urlpatterns = [
    path('index_cde/', views.index_cde, name='index_cde'),
    path('login_cde/', views.login_cde, name='login_cde'),
    path('logout_cde/', views.logout_cde, name='logout_cde'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sistema/libreria/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'libreria'

urlpatterns = [
    path('papeleria/', include(('papeleria.urls', 'papeleria'), namespace='papeleria')),
    path('cafeteria/', include(('cafeteria.urls', 'cafeteria'), namespace='cafeteria')),
    path('cde/', include(('cde.urls', 'cde'), namespace='cde')),

    path('', views.inicio, name='inicio'),
    path('crear_usuario/', views.crear_usuario, name='crear_usuario'),
    path('ver_usuario/<int:user_id>/', views.ver_usuario, name='ver_usuario'),
    path('editar_usuario/<int:user_id>/', views.editar_usuario, name='editar_usuario'),
    path('lista_usuarios/', views.lista_usuarios, name='lista_usuarios'),
    path('cambiar-estado-usuario/<int:user_id>/', views.cambiar_estado_usuario, name='cambiar_estado_usuario'),
    # RESTABLECER CONTRASEÑA 
    path("reset_password/", views.password_reset_request, name="password_reset"),
    path("reset_password/done/", views.password_reset_done, name="password_reset_done"),
    path("reset_password/confirm/<uidb64>/<token>/", views.password_reset_confirm, name="password_reset_confirm"),
    path("reset_password/complete/", views.password_reset_complete, name="password_reset_complete"),

    path('validar_datos/', views.validar_datos, name='validar_datos'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sistema/papeleria/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'papeleria'
urlpatterns = [
   path('index_pap/', views.index_pap, name='index_pap'),
   path('login/papeleria/', views.login_papeleria, name='login_papeleria'),
   path('logout_view/', views.logout_view, name='logout_view'),
   path("crear_articulo/", views.crear_articulo, name="crear_articulo"),
   path("editar_articulo/<int:articulo_id>/", views.editar_articulo, name="editar_articulo"),
   path("listar_articulo/", views.listar_articulo,name="listar_articulo"),
    path('buscar_articulo/', views.buscar_articulo, name='buscar_articulo'),
    path('eliminar_articulo/<int:id>', views.eliminar_articulo, name='eliminar_articulo'),
    path('verificar-nombre-articulo/', views.verificar_nombre_articulo, name='verificar_nombre_articulo'),
    path('validar_datos/', views.validar_datos, name='validar_datos'),
    
     path('reporte_articulo_pdf/', views.reporte_articulo_pdf, name='reporte_articulo_pdf'),
    path('reporte_articulo_excel/', views.reporte_articulo_excel, name='reporte_articulo_excel'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sistema/sistema/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('libreria.urls')),
    path('', include('papeleria.urls')),
    path('', include('cafeteria.urls')),
    path('', include('cde.urls')),
]

sistema/libreria/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser, BaseUserManager, PermissionsMixin, Group, Permission
)

# Create your models here.
class CustomUserManager(BaseUserManager):
    def create_user(self, username, email=None, password=None):
        if not username:
            raise ValueError('El usuario debe tener un nombre de usuario')
        username = username.strip()
        email = self.normalize_email(email) if email else None

        user = self.model(username=username, email=email)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password):
        user = self.create_user(username, email, password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

class CustomUser(AbstractBaseUser, PermissionsMixin):
    ROLES = [
        ('Administrador', 'Administrador'),
        ('Empleado', 'Empleado'),
    ]
    
    MODULES = [
        ('Papeleria', 'Papelería'),
        ('Cafeteria', 'Cafetería'),
        ('Centro de eventos', 'Centro de eventos')
    ]
    username = models.CharField(max_length=100, unique=False)
    email = models.EmailField(unique=True, blank=False, null=False)
    role = models.CharField(max_length=13, choices=ROLES, default='Empleado')
    cargo = models.CharField(max_length=30, default='No establecido')
    module = models.CharField(max_length=30, choices=MODULES, default='papeleria')
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    groups = models.ManyToManyField(Group, related_name="customuser_groups", blank=True)
    user_permissions = models.ManyToManyField(Permission, related_name="customuser_permissions", blank=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'role']

    def __str__(self):
        return self.username
    def get_module_display(self):
        """Devuelve el nombre legible del módulo."""
        return dict(self.MODULES).get(self.module, self.module)

sistema/libreria/forms.py
from django import forms
from .models import CustomUser
class CustomUserForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Contraseña'}),
        required=True
    )
    
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'role', 'cargo', 'module', 'password']

    def __init__(self, *args, **kwargs):
        super(CustomUserForm, self).__init__(*args, **kwargs)
        
        # Agregar clases CSS a los campos
        self.fields['username'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Nombre de usuario'})
        self.fields['email'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Correo electrónico'})
        self.fields['role'].widget.attrs.update({'class': 'form-select'})
        self.fields['cargo'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Cargo'})
        self.fields['module'].widget.attrs.update({'class': 'form-select'})

        # Si el usuario ya existe, deshabilitar el campo 'module' (no puede cambiar su módulo)
        if self.instance.pk:
            self.fields['module'].widget.attrs['disabled'] = True

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if not password:
            raise forms.ValidationError("La contraseña es obligatoria.")
        return password

    def clean_module(self):
        """Si el usuario ya existe, evitar que se cambie el módulo."""
        module = self.cleaned_data.get('module')
        if self.instance.pk:  # Si el usuario ya está registrado
            return self.instance.module  # Mantener el módulo original
        return module

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])  # Encripta la contraseña

        if commit:
            user.save()
        return user
class CustomUserEditForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'role', 'cargo', 'module']

    def __init__(self, *args, **kwargs):
        super(CustomUserEditForm, self).__init__(*args, **kwargs)

        # Hace que los campos sean opcionales
        for field in self.fields:
            self.fields[field].required = False

        # Agrega clases CSS
        self.fields['username'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Nombre de usuario'})
        self.fields['email'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Correo electrónico'})
        self.fields['role'].widget.attrs.update({'class': 'form-select'})
        self.fields['module'].widget.attrs.update({'class': 'form-select'})
        self.fields['cargo'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Cargo'})

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not email:
            return self.instance.email  # Mantiene el valor anterior si no se cambia
        return email

sistema/libreria/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth import authenticate, login
from libreria.forms import CustomUserForm, CustomUserEditForm
from django.shortcuts import get_object_or_404
from .models import CustomUser
from django.contrib.auth import get_user_model
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse
from django.template.loader import render_to_string
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth import logout

from django.http import JsonResponse
from django.db.models import Q
from django.core.paginator import Paginator
# Create your views here.
# Página de inicio
User = get_user_model()
def inicio(request):
    return render(request, 'index/index.html')

def crear_usuario(request):
    admin_exists = CustomUser.objects.exists()

    if request.method == 'POST':
        form = CustomUserForm(request.POST)

        if form.is_valid():
            try:
                user = form.save(commit=False)
                module = user.module
                role = user.role

                # Verificar el número de administradores en cada módulo
                if role == 'Administrador':
                    admin_count = CustomUser.objects.filter(
                        role='Administrador', module=module, is_active=True
                    ).count()

                    limits = {'Papeleria': 3, 'Cafeteria': 2, 'Centro de eventos': 1}
                    if module in limits and admin_count >= limits[module]:
                        messages.error(request, f"Ya existen {limits[module]} administradores en el módulo {module}.")
                        return redirect('crear_usuario')

                # Guardar el usuario
                user.save()

           
                # Enviar correo a los administradores del mismo módulo
                admin_emails = CustomUser.objects.filter(
                    role='Administrador', module=module, is_active=True
                ).values_list('email', flat=True)
                cargo = request.POST.get("cargo", "").strip()
                email = request.POST.get("email", "").strip()
                if admin_emails:
                    subject = f"Nuevo usuario creado en {module}"
                    message = f"Hola querido usuario,\n\nPor parte de Gestor CCD, te informamos que se ha creado un nuevo usuario. \n Información: Nombre: {user.username} \n Rol: {role} Módulo: {module}\n Cargo: {cargo}\n Email: {email}\n\nEn caso de ser infiltrado, por favor te invitamos a desactivarlo.\n\nMuchas gracias por su atención. El director de Gestor CCD te desea un feliz día."
                    send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, list(admin_emails))

                messages.success(request, f"Usuario '{user.username}' creado exitosamente.")
                return redirect('libreria:inicio')

            except Exception as e:
                messages.error(request, f"Hubo un error al crear el usuario: {e}")
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f"{field}: {error}")

    else:
        form = CustomUserForm()

    return render(request, 'usuario/crear_usuario.html', {'form': form, 'admin_exists': admin_exists})

def ver_usuario(request, user_id):
    usuario = get_object_or_404(CustomUser, id=user_id)
    return render(request, 'usuario/ver_perfil.html', {'usuario': usuario})

def editar_usuario(request, user_id):
    usuario = get_object_or_404(CustomUser, id=user_id)

    if request.method == 'POST':
        form = CustomUserEditForm(request.POST, instance=usuario)
        if form.is_valid():
            form.save()
            return redirect('libreria:ver_usuario', user_id=usuario.id)

    else:
        form = CustomUserEditForm(instance=usuario)

    return render(request, 'usuario/editar_usuario.html', {
        'form': form,
        'usuario': usuario
    })
def lista_usuarios(request):
    query = request.GET.get('q', '').strip()
    usuarios_lista = CustomUser.objects.filter(module='papeleria')  # Ordenar por ID

    if query:
        usuarios_lista = usuarios_lista.filter(
            Q(username__icontains=query) |
            Q(email__icontains=query) |
            Q(role__icontains=query) |
            Q(cargo__icontains=query) |
            Q(is_active__icontains=query)
        )

    paginator = Paginator(usuarios_lista, 5)  # Muestra 10 usuarios por página
    page_number = request.GET.get('page')
    usuarios = paginator.get_page(page_number)

    return render(request, 'usuario/lista_usuarios.html', {'usuarios': usuarios})

def cambiar_estado_usuario(request, user_id):
    if request.method == 'POST':
        user = get_object_or_404(CustomUser, id=user_id)
        user.is_active = 'is_active' in request.POST
        user.save()
        return redirect(reverse("libreria:lista_usuarios"))  # Redirige a la página de login



def password_reset_request(request):
    if request.method == "POST":
        email = request.POST.get("email")
        try:
            user = User.objects.get(email=email)
            token = default_token_generator.make_token(user)
            uid = urlsafe_base64_encode(force_bytes(user.pk))
            reset_link = request.build_absolute_uri(
                reverse("libreria:password_reset_confirm", kwargs={"uidb64": uid, "token": token})
            )

            # Enviar correo con el enlace de restablecimiento
            subject = "Restablecer tu contraseña"
            message = render_to_string("password_reset_email.html", {"reset_link": reset_link})
            send_mail(subject, message, "noreply@tuweb.com", [user.email])

            return redirect(reverse("libreria:password_reset_done") + "?sent=true")
        except User.DoesNotExist:
            return redirect(reverse("libreria:password_reset_done") + "?sent=false")

    return render(request, "password_reset.html")


def password_reset_done(request):
    return render(request, "password_reset_done.html")


def password_reset_confirm(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        if request.method == "POST":
            form = SetPasswordForm(user, request.POST)
            if form.is_valid():
                form.save()
                return redirect(reverse("libreria:password_reset_complete"))
        else:
            form = SetPasswordForm(user)
        return render(request, "password_reset_confirm.html", {"form": form})
    else:
        return render(request, "password_reset_confirm.html", {"error": "El enlace no es válido o ha expirado."})


def password_reset_complete(request):
    return render(request, "password_reset_complete.html")

#VALIDAR INFORMACION
def validar_datos(request):
    email = request.GET.get('email', None)
    
    errores = {}

    # Validar correo electrónico
    if email and CustomUser.objects.filter(email=email).exists():
        errores['email'] = 'El email ya está en uso.'

    # Retornar los errores (si los hay) o una respuesta de validación exitosa
    return JsonResponse(errores if errores else {'valid': True})

sistema/libreria/templates/usuario/editar_usuario.html
{% extends 'navbar.html' %}
{% load static %}
{% block titulo %}Editar usuario{% endblock %}

{% block contenido %}
<link rel="stylesheet" href="{% static 'css/editar_usuario.css' %}?v={% now 'U' %}">

<div class="formulario">
    <h1>Editar usuario</h1>
    <form method="POST">
        {% csrf_token %}
        
        <div class="mb-3">
            <label for="username">Nombre de usuario</label>
            <br>{{ form.username }}
        </div>
        <div class="mb-3">
            <label for="email">Correo Electrónico</label>
            <br>{{ form.email }}
        </div>
        <div class="mb-3">
            <label for="role">Rol</label>
            <br>{{ form.role }}
        </div>
        <div class="mb-3">
            <label for="role">Rol</label>
            <br>{{ form.role }}
        </div>
        <div class="mb-3">
            <label for="module">Módulo:</label>
            <br>{{ form.module }}
        </div>
        
        <!-- 🔹 Botón de envío correcto -->
        <button type="submit"  class="btn">Editar</button>

    </form>
</div>
{% endblock %}

sistema/libreria/templates/usuario/lista_usuarios.html
{% extends 'navbar.html' %}
{% load static %}

{% block titulo %}Lista de usuarios{% endblock %}

{% block contenido %}
<link rel="stylesheet" href="{% static 'css/lista_usuarios.css' %}?v={% now 'U' %}">

<div class="fondo">
    <img src="{% static 'imagen/LOGO.png' %}" alt="Logo CCD">
</div>

<section>
    <form method="GET" action="{% url 'libreria:lista_usuarios' %}">
        <input type="text" name="q" id="buscador" placeholder="Buscar ..." class = "buscador "value="{{ request.GET.q }}">
        <button type="submit" class="btn-search"><i data-feather="search" class="icono"></i></button>
    </form>
    
    <div class="Botones">
        <button class="print"><i data-feather="printer" class="icono"></i></button>
        <button class="pdf">PDf</button>
        <button class="excel">Excel</button>
    </div>
    
    <h1>Usuarios de Papelería</h1>
    <table>
        <thead>
            <tr>
                <th class="id">ID</th>
                <th class="nombre">Nombre</th>
                <th class="rol">Rol</th>
                <th class="correo">Correo</th>
                <th class="modulo">Módulo</th>
                <th class="cargo">Cargo</th>
                <th class="estado">Estado</th>
                <th class="actividad">Actividad</th>
                <th class="editar">Editar</th>
            </tr>
        </thead>
        <tbody>
            {% for usuario in usuarios %}
            <tr>
                <td>{{ usuario.id }}</td>
                <td>{{ usuario.username }}</td>
                <td>{{ usuario.role }}</td>
                
                <td>{{ usuario.email }}</td>
                <td>{{ usuario.module }}</td>
                <td>{{ usuario.cargo }}</td>
                <td>{% if usuario.is_active %}Activo{% else %}Inactivo{% endif %}</td>
                <td>
                    <form action="{% url 'libreria:cambiar_estado_usuario' usuario.id %}" method="POST">
                        {% csrf_token %}
                        <label class="cl-switch">
                            <input type="checkbox" name="is_active" {% if usuario.is_active %}checked{% endif %} onchange="this.form.submit()">
                            <span></span>
                        </label>
                    </form>
                </td>
                <td><button class="editar-btn"><i data-feather="edit" class="icono"></i></button></td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="8">No se encontraron usuarios.</td>
            </tr>
            {% endfor %}
        </tbody>
        
    </table>
    <div class="paginacion">
        {% if usuarios.has_previous %}
            <a href="?page=={{ usuarios.previous_page_number }}">Anterior</a>
        {% endif %}
        {% for num in usuarios.paginator.page_range %}
            <a href="?page={{ num }}" class="{% if usuarios.number == num %}active {% endif %}">
                {{ num }}
            </a>
        {% endfor %}
        {% if usuarios.has_next %}
        <a href="?page={{ usuarios.next_page_number }}">Siguiente</a>
    
        {% endif  %}
    </div>
</section>
<script>
    function buscarUsuarios() {
        let query = document.getElementById("buscador").value.trim(); // Obtener texto del input
        let tbody = document.querySelector("tbody");
    
        fetch(`/buscar_usuarios/?q=${query}`)  // Llamar a la API de Django
            .then(response => response.json()) // Convertir respuesta a JSON
            .then(data => {
                tbody.innerHTML = ""; // Limpiar tabla antes de mostrar resultados
                
                data.forEach(usuario => {
                    let fila = `
                        <tr>
                            <td>${usuario.id}</td>
                            <td>${usuario.username}</td>
                            <td>${usuario.role}</td>
                            <td>${usuario.email}</td>
                            <td>${usuario.area}</td>
                            <td>${usuario.is_active ? "Activo" : "Inactivo"}</td>
                            <td>
                                <form action="/cambiar_estado_usuario/${usuario.id}/" method="POST">
                                    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
                                    <label class="cl-switch">
                                        <input type="checkbox" ${usuario.is_active ? "checked" : ""} onchange="this.form.submit()">
                                        <span></span>
                                    </label>
                                </form>
                            </td>
                            <td><button class="editar-btn"><i data-feather="edit" class="icono"></i></button></td>
                        </tr>
                    `;
                    tbody.innerHTML += fila;
                });
            })
            .catch(error => console.error("Error en la búsqueda:", error));
    }
    </script>
    

{% endblock %}

sistema/libreria/templates/usuario/ver_perfil.html
{% extends 'navbar.html' %}
{% load static %}

{% block titulo %}Ver perfil{% endblock %}

{% block contenido %}
<link rel="stylesheet" href="{% static 'css/ver_perfil.css' %}?v={% now 'U' %}"> 

<div class="fondo">
    <img src="{% static 'imagen/LOGO.png' %}" alt="Logo CCD">
</div>

<div class="card">
    <div class="card-body">
        <div class="nombre">
            <label for="username">Nombre de usuario :</label>
            {{ user.username }}
        </div>
        <div class="rol">
            <label for="role">Rol: </label>
            {{ user.role }}
        </div>
        <div class="email">
            <label for="email">Correo:</label>
            {{ user.email }}
        </div>
        <div class="cargo">
            <label for="cargo">Cargo:</label>
            {{ user.cargo }}
        </div>
        <div class="cargo">
            <label for="module">Módulo:</label>
            {{ user.module }}
        </div>
        <div class="botones">
            <a href="{% url 'libreria:editar_usuario' user.id %}"><button class="editar">Editar usuario</button></a>
            
            <a href="{% url 'papeleria:index_pap' %}"><button class="atras">Atrás</button></a>
        </div>
    </div>
</div>

{% endblock %}