sistema/cafeteria/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
app_name = 'cafeteria'
urlpatterns = [
    path('index_caf/', views.index_caf, name='index_caf'),
    path('login/cafeteria/', views.login_cafeteria, name='login_cafeteria'),
    path('logout_caf/', views.logout_caf, name='logout_caf'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sistema/cde/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
app_name = 'cde'
urlpatterns = [
    path('index_cde/', views.index_cde, name='index_cde'),
    path('login_cde/', views.login_cde, name='login_cde'),
    path('logout_cde/', views.logout_cde, name='logout_cde'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sistema/libreria/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'libreria'

urlpatterns = [
    path('papeleria/', include(('papeleria.urls', 'papeleria'), namespace='papeleria')),
    path('cafeteria/', include(('cafeteria.urls', 'cafeteria'), namespace='cafeteria')),
    path('cde/', include(('cde.urls', 'cde'), namespace='cde')),

    path('', views.inicio, name='inicio'),
    path('crear_usuario/', views.crear_usuario, name='crear_usuario'),
    path('ver_usuario/<int:user_id>/', views.ver_usuario, name='ver_usuario'),
    path('editar_usuario/<int:user_id>/', views.editar_usuario, name='editar_usuario'),
    path('lista_usuarios/', views.lista_usuarios, name='lista_usuarios'),
    path('cambiar-estado-usuario/<int:user_id>/', views.cambiar_estado_usuario, name='cambiar_estado_usuario'),
    # RESTABLECER CONTRASEÑA 
    path("reset_password/", views.password_reset_request, name="password_reset"),
    path("reset_password/done/", views.password_reset_done, name="password_reset_done"),
    path("reset_password/confirm/<uidb64>/<token>/", views.password_reset_confirm, name="password_reset_confirm"),
    path("reset_password/complete/", views.password_reset_complete, name="password_reset_complete"),

    path('validar_datos/', views.validar_datos, name='validar_datos'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sistema/sistema/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('libreria.urls')),
    path('', include('papeleria.urls')),
    path('', include('cafeteria.urls')),
    path('', include('cde.urls')),
]

sistema/cafeteria/models.py
from django.db import models

# Create your models here.

sistema/cafeteria/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError
from libreria.models import CustomUser

class LoginForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Correo electrónico'})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Contraseña'})
    )

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get("email")
        password = cleaned_data.get("password")

        if email and password:
            user = authenticate(email=email, password=password)
            
            if user is None:
                raise forms.ValidationError("Usuario o contraseña incorrectos.")
            
            if not user.is_active:
                raise forms.ValidationError("Tu cuenta está inactiva, contacta al administrador.")
        
        return cleaned_data

sistema/cafeteria/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.urls import reverse
from cafeteria.forms import LoginForm 
from django.contrib.auth import get_user_model
def index_caf(request):
    return render(request, 'index_caf/index_caf.html')
# Create your views here.
def login_cafeteria(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, email=email, password=password)

            if user is not None:
                if user.module == 'Cafeteria':  # Verifica que el usuario pertenece a Cafetería
                    login(request, user)
                    messages.success(request, "Sesión iniciada correctamente en Cafetería.")
                    return redirect('cafeteria:index_caf')
                else:
                    messages.error(request, "No tienes acceso a este módulo.")
            else:
                messages.error(request, 'Usuario o contraseña incorrectos.')
    else:
        form = LoginForm()

    return render(request, 'login_caf/login_caf.html', {'form': form})


# CERRAR SESIÓN
def logout_caf(request):
    logout(request)
    messages.success(request, "Has cerrado sesión correctamente.")
    return redirect(reverse('libreria:inicio'))
User = get_user_model()

sistema/cafeteria/templates/login_caf/login_caf.html
{% extends 'navbar.html' %}
{% load static%}
{% block contenido %}
<style>
     .alert {
    padding: 15px;
    margin: 10px 0;
    border-radius: 5px;
    font-weight: bold;
    text-align: center;
    opacity: 0;
    transform: translateY(-10px);
    animation: fadeIn 0.5s ease-in-out forwards;
}


/* Animación de aparición */
@keyframes fadeIn {
    from {
        opacity: 0;
        transform: translateY(-10px);
    }
    to {
        opacity: 1;
        transform: translateY(0);
    }
}

/* Desvanecer después de 5 segundos */
.alert {
    animation: fadeIn 0.5s ease-in-out forwards, fadeOut 0.5s ease-in-out 4.5s forwards;
}

@keyframes fadeOut {
    from {
        opacity: 1;
        transform: translateY(0);
    }
    to {
        opacity: 0;
        transform: translateY(-10px);
    }
}

</style>
<link rel="stylesheet" href="{% static 'css/login_pap.css' %}?v={% now 'U' %}">
<form method="POST" action="{% url 'cafeteria:login_cafeteria' %}" class="login">
    <h3><i data-feather="user"></i>
        Iniciar sesión - Módulo Cafeteria</h3>
    {% csrf_token %}
    <div class="form-group">
        <label for="email">Correo Electrónico</label>
        <input type="email" name="email" id="email" class="form-control" placeholder="Correo electrónico" required>
    </div>
    <div class="form-group">
        <label for="password">Contraseña</label>
        <input type="password" name="password" id="password" class="form-control" placeholder="Contraseña" required>
    </div>
    <button type="submit" class="btn btn-primary btn-block">Iniciar sesión</button>
    <div class="op">
        <a href="{% url 'libreria:crear_usuario' %}">Registrarse</a>
        <a href="{% url 'libreria:password_reset' %}">¿Olvidaste la contraseña?</a>
    </div>
</form>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert" style="color: rgb(255, 0, 0); font-weight: bold; background-color: rgb(245, 134, 134); width: 40vh; align-items: center; left: 85vh; position: absolute; top: 20vh;"  >
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
{% endblock %}