sistema/cde/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
app_name = 'cde'
urlpatterns = [
    path('index_cde/', views.index_cde, name='index_cde'),
    path('login_cde/', views.login_cde, name='login_cde'),
    path('logout_cde/', views.logout_cde, name='logout_cde'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sistema/papeleria/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'papeleria'
urlpatterns = [
   path('index_pap/', views.index_pap, name='index_pap'),
   path('login/papeleria/', views.login_papeleria, name='login_papeleria'),
   path('logout_view/', views.logout_view, name='logout_view'),
   path("crear_articulo/", views.crear_articulo, name="crear_articulo"),
   path("editar_articulo/<int:articulo_id>/", views.editar_articulo, name="editar_articulo"),
   path("listar_articulo/", views.listar_articulo,name="listar_articulo"),
    path('buscar_articulo/', views.buscar_articulo, name='buscar_articulo'),
    path('eliminar_articulo/<int:id>', views.eliminar_articulo, name='eliminar_articulo'),
    path('verificar-nombre-articulo/', views.verificar_nombre_articulo, name='verificar_nombre_articulo'),
    path('validar_datos/', views.validar_datos, name='validar_datos'),
    
     path('reporte_articulo_pdf/', views.reporte_articulo_pdf, name='reporte_articulo_pdf'),
    path('reporte_articulo_excel/', views.reporte_articulo_excel, name='reporte_articulo_excel'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sistema/sistema/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('libreria.urls')),
    path('', include('papeleria.urls')),
    path('', include('cafeteria.urls')),
    path('', include('cde.urls')),
]

sistema/papeleria/models.py
from django.db import models
from django.conf import settings
# Create your models here.
class Articulo(models.Model):
    nombre = models.CharField(max_length=100, unique=True)
    marca = models.CharField(max_length=50, null=False, blank=False)
    observacion = models.TextField(blank=True, null=True)
    tipo = models.CharField(max_length=50, null=False, blank=False, default='No establecido')
    precio = models.PositiveBigIntegerField(null=False, blank=False)
    cantidad = models.PositiveIntegerField()
    registrado_por = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True,blank=True)
    fecha_registro = models.DateField(auto_now=True)
    def __str__(self):
        return self.nombre
    def observacion_formateada(self, longitud=20):  # 'self' es necesario, longitud es opcional
        if not self.observacion:  # Usa self.observacion
            return ""
        return '\n'.join(self.observacion[i:i + longitud] for i in range(0, len(self.observacion), longitud))

sistema/papeleria/forms.py
from django import forms
from papeleria.models import Articulo

from django.contrib.auth import authenticate
class LoginForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Correo electrónico'})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Contraseña'})
    )
class ArticuloForm(forms.ModelForm):
        class Meta:
            model = Articulo
            fields = ['nombre', 'marca', 'observacion', 'precio', 'cantidad',    'tipo']

class ArticuloEditForm(forms.ModelForm):    
    class Meta:
        model = Articulo
        fields = ['nombre', 'marca', 'observacion', 'precio', 'cantidad', 'tipo']
    def __init__(self, *args,**kwargs):
        super(ArticuloEditForm, self).__init__(*args, **kwargs)
        # Hace que los campos sean opcionales
        self.fields['nombre'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Nombre del articulo'})
        self.fields['marca'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Marca del articulo'})
        self.fields['observacion'].widget.attrs.update({'class':'form-control', 'placeholder': 'Observación' })
        self.fields['precio'].widget.attrs.update({'class':'form-control', 'placeholder': 'Precio del  articulo'})
        self.fields['cantidad'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Cantidad de articulo'})
        self.fields['tipo'].widget.attrs.update({'class':'form-control', 'placeholder': 'Tipo de articulo'})
    
    def clean(self):
        cleaned_data = super().clean()
        
        # Mantener valores anteriores si no se proporciona un nuevo valor
        for field in self.fields:
            if not cleaned_data.get(field):
                cleaned_data[field] = getattr(self.instance, field)

        return cleaned_data

sistema/papeleria/views.py
from django.shortcuts import render
from papeleria.models import Articulo
from libreria.models import CustomUser
from papeleria.forms import LoginForm, ArticuloForm, ArticuloEditForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.template.loader import get_template
from django.utils.timezone import now
from django.http import HttpResponse
from xhtml2pdf import pisa
from io import BytesIO
# Create your views here.
def index_pap(request):
    breadcrumbs = [
        {'name': 'Inicio', 'url': '/index_pap'},
    ]
    return render(request, 'index_pap/index_pap.html', {'breadcrumbs': breadcrumbs})
def login_papeleria(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, email=email, password=password)

            if user is not None:
                if user.module == 'Papeleria':  # Verifica que el usuario pertenece a Papelería
                    login(request, user)
                    messages.success(request, "Sesión iniciada correctamente en Papelería.")
                    return redirect('papeleria:index_pap')  # Redirige a la página de inicio de Papelería
                else:
                    messages.error(request, "No tienes acceso a este módulo.")
            else:
                messages.error(request, 'Usuario o contraseña incorrectos.')
    else:
        form = LoginForm()

    return render(request, 'login_pap/login_pap.html', {'form': form})

# CERRAR SESIÓN
def logout_view(request):
    logout(request)
    messages.success(request, "Has cerrado sesión correctamente.")
    return redirect(reverse('libreria:inicio'))
User = get_user_model()


def crear_articulo(request):
    if request.method == 'POST':
        form = ArticuloForm(request.POST)
        if form.is_valid():  # Corrección aquí
            articulo = form.save(commit=False)
            articulo.registrado_por = request.user
            articulo.save()
            return redirect('papeleria:listar_articulo')  # Redirección correcta
    else:
        form = ArticuloForm()
    
    return render(request, 'articulo/crear_articulo.html', {'form': form})
def editar_articulo(request, articulo_id):
    articulo = get_object_or_404(Articulo, id=articulo_id)
    if request.method== 'POST':
        form = ArticuloEditForm(request.POST, instance=articulo)
        if form.is_valid():
            form.save()
            return redirect('papeleria:listar_articulo')
    else:
            form = ArticuloEditForm(instance=articulo)
    return render(request, 'articulo/editar_articulo.html', {'form': form, 'articulo': articulo})


def listar_articulo(request):
    query = request.GET.get('q', '').strip()
    articulos = Articulo.objects.select_related('registrado_por').all()


    if query:
        articulos = articulos.filter(
        Q(nombre__icontains=query) |
        Q(marca__icontains=query) |
        Q(observacion__icontains=query) |
        Q(tipo__icontains=query) |
        Q(precio__icontains=query) |
        Q(cantidad__icontains=query) |
        Q(registrado_por__username__icontains=query) |
        Q(fecha_registro__icontains=query)
    )

    paginator = Paginator(articulos, 5)
    page_number = request.GET.get('page')
    articulos = paginator.get_page(page_number)

    return render(request, 'articulo/listar_articulo.html', {'articulos': articulos})
def buscar_articulo(request):
    query = request.GET.get('q', '').strip()
    if query:
        articulos = Articulo.objects.filter(nombre__icontains=query).values(
            'id', 'nombre', 'marca', 'observacion', 'precio', 'registrado_por', 'fecha_registro'
        )
        return JsonResponse(list(articulos), safe=False)
    return JsonResponse([], safe=False)

def eliminar_articulo(request, id):
    articulo = Articulo.objects.get(id=id)
    if request.method == 'POST':
        articulo.delete()
        messages.success(request, "Artículo eliminado correctamente.")
    return redirect('papeleria:listar_articulo')


def validar_datos(request):
    email = request.GET.get('email', None)
    
    errores = {}

    # Validar correo electrónico
    if email and CustomUser.objects.filter(email=email).exists():
        errores['email'] = 'El email ya está en uso.'

    # Retornar los errores (si los hay) o una respuesta de validación exitosa
    return JsonResponse(errores if errores else {'valid': True})
def verificar_nombre_articulo(request):
    nombre = request.GET.get('nombre', '')
    existe = Articulo.objects.filter(nombre=nombre).exists()
    return JsonResponse({'existe': existe})

from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter, landscape
from django.contrib.staticfiles import finders
from reportlab.lib import colors  
from reportlab.platypus import Table, TableStyle
from reportlab.lib.units import inch
from datetime import datetime


def reporte_articulo_pdf(request):
    buffer = BytesIO()
    p = canvas.Canvas(buffer, pagesize=landscape(letter))
    width, height = landscape(letter)

    margin = 40
    table_width = width - 2 * margin
    y_position = height - margin - 110

    # Marca de agua
    watermark_path = finders.find('imagen/LOGO.png')
    p.saveState()
    p.setFillColor(colors.Color(1, 1, 1, alpha=0.3))
    p.setStrokeColor(colors.Color(1, 1, 1, alpha=0.3))
    p.drawImage(watermark_path, x=(width - 600) / 2, y=(height - 600) / 2, width=600, height=600, mask='auto')
    p.restoreState()

    # Título
    fecha_actual = datetime.now().strftime("%d/%m/%Y")
    p.setFont("Helvetica-Bold", 16)
    p.drawCentredString(width / 2, height - margin - 30, "REPORTE DE ARTÍCULOS")

    # Encabezado de empresa
    tabla_encabezado = Table([
        ["GESTOR CCD", "Lista de artículos", "Correo:", f"Fecha: {fecha_actual}"],
        ["Cámara de comercio de Duitama", "Nit: 123456789", "contacto@gestorccd.com", "Teléfono: (123) 456-7890"],
    ], colWidths=[180, 180, 180, 180])

    estilo_encabezado = TableStyle([
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#5564eb")),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTNAME', (0, 1), (-1, 1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
    ])
    tabla_encabezado.setStyle(estilo_encabezado)
    tabla_encabezado.wrapOn(p, table_width, height)
    tabla_encabezado.drawOn(p, margin, y_position)

    # Tabla del usuario autenticado (justo debajo del encabezado)
    usuario = request.user
    data_usuario = [["Usuario", "Email", "Rol", "Cargo"]]
    data_usuario.append([
        usuario.username,
        usuario.email,
        getattr(usuario, 'role', 'No definido'),
        usuario.cargo
    ])

    table_usuario = Table(data_usuario, colWidths=[180, 180, 180, 180])
    style_usuario = TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#5564eb")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTNAME', (0, 1), (-1, 1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
    ])
    table_usuario.setStyle(style_usuario)
    table_usuario.wrapOn(p, table_width, height)

    # Calcular la altura ocupada por el encabezado para colocar al usuario pegado debajo
    alto_encabezado = len(tabla_encabezado._cellvalues) * 18
    y_tabla_usuario = y_position - alto_encabezado -12 # Espacio adicional de 20 unidades
    table_usuario.drawOn(p, margin, y_tabla_usuario)

    # Tabla de artículos (pegada debajo del usuario)
    data_articulos = [["ID", "Nombre", "Marca", "Tipo", "Precio", "Cantidad", "Observación"]]
    articulos = Articulo.objects.all()
    for articulo in articulos:
        data_articulos.append([
            articulo.id,
            articulo.nombre,
            articulo.marca,
            articulo.tipo,
            articulo.precio,
            articulo.cantidad,
            articulo.observacion
        ])

    table = Table(data_articulos, colWidths=[70, 100, 100, 90, 90, 90, 180])
    style = TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#5564eb")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        
        ('TEXTCOLOR', (0, 1), (-1, -1), colors.black),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ])
    table.setStyle(style)
    table.wrapOn(p, table_width, height)

    alto_usuario = len(data_usuario) * 18
    y_tabla_articulos = y_tabla_usuario - alto_usuario-45
    table.drawOn(p, margin, y_tabla_articulos)

    # Finalizar PDF
    p.showPage()
    p.save()

    buffer.seek(0)
    response = HttpResponse(buffer.getvalue(), content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="Reporte_articulos.pdf"'
    return response
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side
from openpyxl import Workbook
from openpyxl.drawing.image import Image

sistema/papeleria/templates/articulo/crear_articulo.html
{% extends 'navbar.html' %}
{% load static %}
{% block titulo %}Crear artículos{% endblock %}
{% block contenido %}
<link rel="stylesheet" href="{% static 'css/crear_articulo.css' %}?v={% now 'U' %}">
<style>
    .disabled { 
        opacity: 0.5; 
        cursor: not-allowed; 
    }

    /* Clases específicas para cada mensaje de error */
    .error-nombre {
        color: rgb(255, 0, 0);   /* Color rojo para los errores */
        font-size: 14px;          /* Ajusta el tamaño de la fuente */
        font-weight: bold;  
        position: absolute;      /* Negrita */
        top: 45vh;
    }

    .error-marca {
        color: rgb(255, 0, 0);   /* Color rojo para los errores */
        font-size: 14px;          /* Ajusta el tamaño de la fuente */
        font-weight: bold;        /* Negrita */
    }

    .error-precio {
        color: rgb(255, 0, 0);   /* Color rojo para los errores */
        font-size: 14px;          /* Ajusta el tamaño de la fuente */
        font-weight: bold;        /* Negrita */
    }

    .error-cantidad {
        color: rgb(255, 0, 0);   /* Color rojo para los errores */
        font-size: 14px;          /* Ajusta el tamaño de la fuente */
        font-weight: bold;        /* Negrita */
        position: absolute;
        height: -5vh;
    }

    .error-observacion {
        color: rgb(255, 0, 0);   /* Color rojo para los errores */
        font-size: 14px;          /* Ajusta el tamaño de la fuente */
        font-weight: bold;        /* Negrita */
    }

    /* Puedes agregar más estilos específicos si lo necesitas */
    #nombre_error {
        position: absolute;
        top: 26vh;
        left: 9vh;
    }

    #marca_error {
        position: absolute;
        top: 32vh;
        left: 9vh;
    }

    #precio_error, #cantidad_error, #observacion_error {
        font-size: 14px;
    }
</style>
<div class="fondo">
    <img src="{% static 'imagen/LOGO.png' %}" alt="Logo CCD">
</div>
<div class="formulario">
    <h2>Crear artículo</h2>
    <form method="POST" id="form_articulo">
        {% csrf_token %}
        <div class="mb-3">
            <label for="nombre" class="form-label">Nombre del artículo</label>
            <input type="text" name="nombre" id="nombre" class="form-control" required autocomplete="off" placeholder="Digite el nombre del artículo">
            <div id="nombre_error" class="error-nombre"></div>
        </div>
        <div class="mb-3">
            <label for="tipo" class="form-label">Digite el tipo de articulo</label>
            <input type="text" name="tipo" id="tipo" placeholder="Digite el tipo del artículo">
            
        </div>
        <div class="mb-3">
            <label for="marca" class="form-label">Marca del artículo</label>
            <input type="text" name="marca" id="marca" class="form-control" required autocomplete="off" placeholder="Digite la marca del artículo">
            <div id="marca_error" class="error-marca"></div>
        </div>
        <div class="mb-3">
            <label for="precio" class="form-label">Digite el precio</label>
            <input type="text" name="precio" id="precio" placeholder="Digite el precio del artículo">
            <div id="precio_error" class="error-precio"></div>
        </div>
        <div class="mb-3">
            <label for="cantidad" class="form-label">Digite la cantidad</label>
            <input type="number" name="cantidad" id="cantidad" placeholder="Digite la cantidad del artículo">
            <div id="cantidad_error" class="error-cantidad"></div>
        </div>
        <div class="mb-3">
            <label for="observacion" class="form-label">Observación del artículo</label>
            <input type="text" name="observacion" id="observacion" class="form-control" placeholder="Digite alguna observación del artículo">
            <div id="observacion_error" class="error-observacion"></div>
        </div>
        <button type="submit" class="btn disabled" id="submit_btn" disabled>Registrar artículo</button>
    </form>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    // Funciones de validación
    const validateNombre = () => {
        const nombre = $('#nombre').val();
        const regex = /^[a-zA-Z\s]+$/; // Solo letras y espacios
        if (nombre && !regex.test(nombre)) {
            $('#nombre_error').text('Solo se permiten letras y espacios.');
            return false;
        } else {
            $('#nombre_error').text('');
            return true;
        }
    };

    const validateMarca = () => {
        const marca = $('#marca').val();
        const regex = /^[a-zA-Z\s]+$/; // Solo letras y espacios
        if (marca && !regex.test(marca)) {
            $('#marca_error').text('Solo se permiten letras y espacios.');
            return false;
        } else {
            $('#marca_error').text('');
            return true;
        }
    };

    const validatePrecio = () => {
        const precio = $('#precio').val();
        const regex = /^[0-9]+$/; // Solo números
        if (precio && !regex.test(precio)) {
            $('#precio_error').text('Solo se permiten números.');
            return false;
        } else {
            $('#precio_error').text('');
            return true;
        }
    };

    const validateCantidad = () => {
        const cantidad = $('#cantidad').val();
        if (cantidad < 1) {
            $('#cantidad_error').text('La cantidad no puede ser menor a 1.');
            return false;
        } else {
            $('#cantidad_error').text('');
            return true;
        }
    };

    const validateObservacion = () => {
        const observacion = $('#observacion').val();
        $('#observacion_error').text('');
        return true;
    };

    const enableSubmitButton = () => {
        const isValid = validateNombre() && validateMarca() && validatePrecio() && validateCantidad() && validateObservacion();
        const submitBtn = $('#submit_btn');
        if (isValid) {
            submitBtn.removeClass('disabled').prop('disabled', false);
        } else {
            submitBtn.addClass('disabled').prop('disabled', true);
        }
    };

    // Validación en tiempo real
    $('#nombre, #marca, #precio, #cantidad, #observacion').on('input', function() {
        enableSubmitButton();
    });

    // AJAX para verificar si el nombre del artículo ya está registrado
    $('#nombre').on('input', function() {
        const nombre = $('#nombre').val();
        if (nombre.length > 2) {  // Verifica solo después de digitar más de 2 caracteres
            $.ajax({
                url: '{% url "papeleria:validar_datos" %}',  // Cambia esta URL según tu vista
                method: 'GET',
                data: { tipo: 'nombre', valor: nombre },  // Enviar tipo y valor
                success: function(response) {
                    if (response.nombre) {
                        $('#nombre_error').text(response.nombre);
                    } else {
                        $('#nombre_error').text('');
                    }
                }
            });
        }
    });

    $(document).ready(function() {
        enableSubmitButton();
    });
</script>

{% endblock %}

sistema/papeleria/templates/articulo/editar_articulo.html
{% extends 'navbar.html' %}
{% load static %}
{% block titulo %}Editar articulos{% endblock %}
{% block contenido %}
<div class="fondo">
    <img src="{% static 'imagen/LOGO.png' %}" alt="Logo CCD">
</div>
<div class="formulario">
    <h2>Editar artículo</h2>
    <form method="POST" id="form_articulo" action="{% url 'papeleria:editar_articulo' articulo.id %}">


        {% csrf_token %}
        <div class="mb-3">
            <label for="nombre" class="form-label">Nombre del artículo</label>
            {{ form.nombre }}
        </div>
        <div class="mb-3">
            <label for="tipo" class="form-label">Digite el tipo de articulo</label>
            {{ form.tipo }}
            
        </div>
        <div class="mb-3">
            <label for="marca" class="form-label">Marca del artículo</label>
            {{ form.marca}}
        </div>
        <div class="mb-3">
            <label for="precio" class="form-label">Digite el precio</label>
            {{ form.precio }}
        </div>
        <div class="mb-3">
            <label for="cantidad" class="form-label">Digite la cantidad</label>
            {{ form.cantidad }}
        </div>
        <div class="mb-3">
            <label for="observacion" class="form-label">Observación del artículo</label>
            {{ form.observacion }}
        </div>
        <button type="submit">Editar artículo</button>
    </form>
</div>
{% endblock%}

sistema/papeleria/templates/articulo/listar_articulo.html
{% extends 'navbar.html' %}
{% load static %}
{% block titulo %}Listar articulos{% endblock %}
{% block contenido %}
<link rel="stylesheet" href="{% static 'css/listar_articulo.css' %}">
<div class="fondo">
    <img src="{% static 'imagen/LOGO.png' %}" alt="Logo CCD">
</div>
<section>
    <form method="GET"  action="{% url 'papeleria:listar_articulo' %}">
        <input type="text" name="q" id="buscador" placeholder="Buscar ..." class="buscador" value="{{ request.GET.q }}">
        <button type="submit" class="btn-search"><i data-feather="search" class="icono"></i></button>
    </form>
<div class="Bototnes">
    <button class="print"><i data-feather="printer"class="icono "></i></button>
    <a href="{% url 'papeleria:reporte_articulo_pdf' %}"><button class="pdf">PDF</button></a>
    <a href="{% url 'papeleria:reporte_articulo_excel' %}"><button class="excel">Excel</button></a>
</div>
<h1>Articulos de papeleria</h1>
<table>
    <thead>
        <tr>
            <th class="id">ID</th>
            <th class="nombre">Nombre</th>
            <th class="marca">Marca</th>
            <th class="observacion">Observacion</th>
            <th class="precio">Precio</th>
            <th class="estado">Registrado por</th>
            <th class="actividad">Fecha de regiztro</th>
            <th class="editar">Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for articulo in articulos %}
        <tr>
            <td>{{ articulo.id }}</td>
        <td>{{ articulo.nombre }}</td>
        <td>{{ articulo.marca }}</td>
        <td>{{ articulo.observacion }}</td>
        <td>{{ articulo.precio }}</td>
        <td>{{ articulo.registrado_por }}</td>
        <td>{{ articulo.fecha_registro }}</td>
        <td>
            <a href="{% url 'papeleria:editar_articulo' articulo.id %}"><button class="editar-btn"><i data-feather="edit" class="icono"></i></button></a>
            <button class="eliminar-btn" onclick="mostrarModal('{{ articulo.id }}')">
                <i data-feather="trash-2" class="icono"></i>
            </button>
            
        </td>
    </tr>
        {% empty %}
        <tr>
            <td colspan="8">No se encontraron resultados</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<div class="paginacion">
    {% if articulos.has_previous %}
        <a href="?page={{ articulos.previous_page_number }}" class="prev">Anterior</a>
    {% endif %}

    {% for num in articulos.paginator.page_range %}
        {% if articulos.number == num %}
            <span class="current">{{ num }}</span>
        {% else %}
            <a href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}

    {% if articulos.has_next %}
        <a href="?page={{ articulos.next_page_number }}" class="next">Siguiente</a>
    {% endif %}
</div>
<div id="modoEliminar" class="modal" style="display: none;">
    <div class="modal-contenido">
        <h2>¿Estás seguro de eliminar este articulo'</h2>
        <form id="formEliminar" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn-delete">Eliminar</button>
            <button class="back" type="button" onclick="cerrarModal()" >Cancelar</button>
        </form>
    </div>
</div>
</section>
<script>
    function buscarArticulo(){
        let query = document.getElementById("buscador").value.trim();
        let tbody = document.querySelector("tbody");
        fetch(`{% url 'papeleria:buscar_articulo' %}?q=${query}`)
        .then(response=> response.json())
        .then(data =>{
            tbody.innerHTML = "";
            data.forEach(articulo => {
                let fila = `
                <tr>
                    <td>${articulo.id}</td>
                    <td>${articulo.nombre}</td>
                    <td>${articulo.marca}</td>
                    <p>{{ articulo.observacion_formateada }}</p
                    <td>${articulo.precio}</td>
                    <td>${articulo.registrado_por}</td>
                    <td>${articulo.fecha_registro}</td>
                    <td>
                        <button class="editar-btn"><i data-feather="edit" class="icono"></i></button>
                        <button class="eliminar-btn"><i data-feather="trash-2"></i></button>
                    </td>
                </tr>
                `;
                tbody.innerHTML += fila;
            });
            
        })
        .catch(error => console.error(error));
    }

function mostrarModal(id){
    const modal = document.getElementById("modoEliminar");
    const formEliminar = document.getElementById("formEliminar");
    formEliminar.action = `{% url 'papeleria:eliminar_articulo' 0 %}`.replace(/0/, id);
    modal.style.display = "block";
}
function cerrarModal(){
    const modal = document.getElementById("modoEliminar");
    modal.style.display = "none";
}
</script>
{% endblock%}