sistema/cde/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
app_name = 'cde'
urlpatterns = [
    path('index_cde/', views.index_cde, name='index_cde'),
    path('login_cde/', views.login_cde, name='login_cde'),
    path('logout_cde/', views.logout_cde, name='logout_cde'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sistema/libreria/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'libreria'

urlpatterns = [
    path('papeleria/', include(('papeleria.urls', 'papeleria'), namespace='papeleria')),
    path('cafeteria/', include(('cafeteria.urls', 'cafeteria'), namespace='cafeteria')),
    path('cde/', include(('cde.urls', 'cde'), namespace='cde')),

    path('', views.inicio, name='inicio'),
    path('crear_usuario/', views.crear_usuario, name='crear_usuario'),
    path('ver_usuario/<int:user_id>/', views.ver_usuario, name='ver_usuario'),
    path('editar_usuario/<int:user_id>/', views.editar_usuario, name='editar_usuario'),
    path('lista_usuarios/', views.lista_usuarios, name='lista_usuarios'),
    path('cambiar-estado-usuario/<int:user_id>/', views.cambiar_estado_usuario, name='cambiar_estado_usuario'),
    # RESTABLECER CONTRASEÑA 
    path("reset_password/", views.password_reset_request, name="password_reset"),
    path("reset_password/done/", views.password_reset_done, name="password_reset_done"),
    path("reset_password/confirm/<uidb64>/<token>/", views.password_reset_confirm, name="password_reset_confirm"),
    path("reset_password/complete/", views.password_reset_complete, name="password_reset_complete"),

    path('validar_datos/', views.validar_datos, name='validar_datos'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sistema/papeleria/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'papeleria'
urlpatterns = [
   path('index_pap/', views.index_pap, name='index_pap'),
   path('login/papeleria/', views.login_papeleria, name='login_papeleria'),
   path('logout_view/', views.logout_view, name='logout_view'),
   path("crear_articulo/", views.crear_articulo, name="crear_articulo"),
   path("editar_articulo/<int:articulo_id>/", views.editar_articulo, name="editar_articulo"),
   path("listar_articulo/", views.listar_articulo,name="listar_articulo"),
    path('buscar_articulo/', views.buscar_articulo, name='buscar_articulo'),
    path('eliminar_articulo/<int:id>', views.eliminar_articulo, name='eliminar_articulo'),
    path('verificar-nombre-articulo/', views.verificar_nombre_articulo, name='verificar_nombre_articulo'),
    path('validar_datos/', views.validar_datos, name='validar_datos'),
    
     path('reporte_articulo_pdf/', views.reporte_articulo_pdf, name='reporte_articulo_pdf'),
    path('reporte_articulo_excel/', views.reporte_articulo_excel, name='reporte_articulo_excel'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sistema/sistema/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('libreria.urls')),
    path('', include('papeleria.urls')),
    path('', include('cafeteria.urls')),
    path('', include('cde.urls')),
]

sistema/cde/models.py
from django.db import models

# Create your models here.

sistema/cde/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError
from libreria.models import CustomUser
class LoginForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Correo electrónico'})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Contraseña'})
    )

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get("email")
        password = cleaned_data.get("password")

        if email and password:
            user = authenticate(email=email, password=password)
            
            if user is None:
                raise forms.ValidationError("Usuario o contraseña incorrectos.")
            
            if not user.is_active:
                raise forms.ValidationError("Tu cuenta está inactiva, contacta al administrador.")
        
        return cleaned_data

sistema/cde/views.py
from django.shortcuts import render
from cde.forms import LoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import get_user_model
# Create your views here.
def login_cde(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, email=email, password=password)

            if user is not None:
                if user.module == 'Centro de eventos':  # Verifica que el usuario pertenece a CDE
                    login(request, user)
                    messages.success(request, "Sesión iniciada correctamente en CDE.")
                    return redirect('cde:index_cde')  # Redirige a la página de inicio de CDE
                else:
                    messages.error(request, "No tienes acceso a este módulo.")
            else:
                messages.error(request, 'Usuario o contraseña incorrectos.')
    else:
        form = LoginForm()

    return render(request, 'login_cde/login_cde.html', {'form': form})

def logout_cde(request):
    logout(request)
    messages.success(request, "Has cerrado sesión correctamente.")
    return redirect(reverse('libreria:inicio'))
User = get_user_model()

def index_cde(request):
    return render(request, 'index_cde/index_cde.html')

sistema/cde/templates/index_cde/index_cde.html
{% extends 'navbar.html' %}
{% load static %}

{% block titulo %}Inicio{% endblock %}

{% block contenido %}
<link rel="stylesheet" href="{% static 'css/index_pap.css' %}?v={% now 'U' %}">

<div class="fondo">
    <img src="{% static 'imagen/LOGO.png' %}" alt="Logo CCD">
</div>
<div class="uno">
    <a href="{% url 'libreria:crear_usuario' %}"><div class="opcion">
        <i data-feather="user-plus" class="icono"></i>
        <span>Crear usuario</span>
    </div></a>
    <a href="#">
        <div class="opcion">
            <i data-feather="plus-square" class="icono"></i>
            <span>Ver perfil</span>
        </div>
    </a>
    
    <a href="#">
        <div class="opcion">
            <i data-feather="users" class="icono"></i>
            <span>Lista de usuarios</span>
        </div>
    </a>
    <a href="#"><div class="opcion">
        <i data-feather="user-plus" class="icono"></i>
        <span>Crear articulo</span>
    </div></a>
    <a href="#">
        <div class="opcion">
            <i data-feather="package" class="icono"></i>
            <span>Listar articulos</span>
        </div>
    </a>
    <div class="opcion">
        <i data-feather="refresh-ccw" class="icono"></i>
        <span>Movimientos</span>
    </div>
    <div class="opcion">
        <i data-feather="briefcase" class="icono"></i>
        <span></span>
    </div>
    <div class="opcion">
        <i data-feather="alert-triangle" class="icono"></i>
        <span>Articulos con bajo stock</span>
    </div>
    <div class="opcion">
        <i data-feather="bar-chart" class="icono"></i>
        <span>Estadisticas</span>
    </div>
    <div class="opcion">
        <i data-feather="lock" class="icono"></i>
        <span>Cambiar contraseña</span>
    </div>
    <a href="{% url 'papeleria:logout_view' %}">
        <div class="opcion">
            <i data-feather="log-out" class="icono"></i>
            <span>Salir</span>
        </div>
    </a>
</div>

<script>
    feather.replace();
</script>

{% endblock %}